"""Sync georef from PixelTable cycle output and apply into active VW working copy.

Run this inside Vectorworks Python so `vs` is available to the apply/audit scripts.
"""

from __future__ import annotations

import json
import os
import runpy
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path("/Volumes/PixelTable/VW_iTwin_Bridge/VW_iTwin_Bridge")
MARPA_PROJECT_ROOT = Path("/Volumes/PixelTable/GROVE_HARNESS/juniper2026")

CYCLE_SCRIPT = ROOT / "pixeltable/scripts/run_farber_haines_georef_cycle.py"
PIXELTABLE_VENV_PYTHON = ROOT / "pixeltable/.venv/bin/python"
APPLY_SCRIPT = MARPA_PROJECT_ROOT / "vw_plugins/apply_document_georef.py"
AUDIT_SCRIPT = MARPA_PROJECT_ROOT / "vw_plugins/audit_georeference.py"

FIT_JSON = Path("/tmp/farber_haines_georef_fit.json")
BINDING_CANDIDATE_JSON = Path("/tmp/farber_haines_georef_binding_candidate.json")
RUNTIME_BINDING_JSON = (
    ROOT
    / "projects/farber-haines-2521/artifacts/georef/document_georef_binding.runtime.json"
)
SYNC_REPORT_JSON = (
    ROOT / "projects/farber-haines-2521/artifacts/georef/farber_haines_vw_sync_report.json"
)


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def build_runtime_binding() -> dict:
    candidate = load_json(BINDING_CANDIDATE_JSON) if BINDING_CANDIDATE_JSON.exists() else {}
    fit = load_json(FIT_JSON) if FIT_JSON.exists() else {}
    epsg_code = int(
        candidate.get("epsg_code")
        or fit.get("target_epsg_code")
        or 2876
    )
    rmse = fit.get("fit_rmse_project_units")
    max_residual = fit.get("fit_max_residual_project_units")
    return {
        "_origin": "runtime Farber-Haines VW sync binding generated from latest cycle fit",
        "binding_id": "document_georef_binding_runtime",
        "binding_status": "runtime_apply",
        "allow_apply": True,
        "binding_kind": "runtime_sync_set_doc_georef_by_usr_org",
        "control_point_id": "anchor_wgs84_reference",
        "epsg_code": epsg_code,
        "set_user_origin_mode": "skip",
        "survey_point_origin_x": 0.0,
        "survey_point_origin_y": 0.0,
        "notes": (
            "Generated by run_farber_haines_sync_georef_working_copy.py from cycle outputs. "
            f"fit_rmse={rmse}, fit_max_residual={max_residual}. "
            "This writes persistent document georef into VW via SetDocGeoRefByUsrOrg."
        ),
    }


def run_cycle() -> dict:
    uv_bin = shutil.which("uv") or "/Users/ojeromyo/.local/bin/uv"
    if Path(uv_bin).exists():
        cmd = [uv_bin, "run", "python", str(CYCLE_SCRIPT), "--apply-fit"]
    else:
        cmd = [str(PIXELTABLE_VENV_PYTHON), str(CYCLE_SCRIPT), "--apply-fit"]
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "georef cycle failed: "
            + (result.stderr.strip() if result.stderr else result.stdout.strip())
        )
    return json.loads(result.stdout)


def main() -> None:
    started_at = now_iso()
    cycle_report = run_cycle()
    runtime_binding = build_runtime_binding()
    RUNTIME_BINDING_JSON.parent.mkdir(parents=True, exist_ok=True)
    RUNTIME_BINDING_JSON.write_text(
        json.dumps(runtime_binding, indent=2),
        encoding="utf-8",
    )

    os.environ["MARPA_PROJECT_ROOT"] = str(MARPA_PROJECT_ROOT)
    os.environ["APPLY_DOCUMENT_GEOREF_FORCE_MODE"] = "apply"
    os.environ["APPLY_DOCUMENT_GEOREF_BINDING_PATH"] = str(RUNTIME_BINDING_JSON)
    os.environ["APPLY_DOCUMENT_GEOREF_FORCE_REQUIRE_RESOLVED_BINDING"] = "false"

    runpy.run_path(str(APPLY_SCRIPT), run_name="__main__")
    runpy.run_path(str(AUDIT_SCRIPT), run_name="__main__")

    report = {
        "ok": True,
        "started_at": started_at,
        "finished_at": now_iso(),
        "cycle_report_path": str(
            ROOT / "projects/farber-haines-2521/artifacts/georef/farber_haines_georef_cycle_report.json"
        ),
        "runtime_binding_path": str(RUNTIME_BINDING_JSON),
        "cycle_report": cycle_report,
    }
    SYNC_REPORT_JSON.write_text(json.dumps(report, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
