"""0015 — Pixeltable knowledge substrate (Amendment 07).

Creates `lattice/knowledge/*` — the substrate that backs the anti-amnesia
rule. Tutorials (YouTube + local video) are ingested, audio extracted,
transcribed via Whisper, then split into sentences and embedded. Research
docs are ingested as Pixeltable Documents, chunked via DocumentSplitter,
and embedded. Skills generated by the harvest pipeline are registered so
the harness can ask "what skill exists for tool X?".

What this migration creates:

  lattice/knowledge/                         (new namespace)
  lattice/knowledge/tutorials                — Video + computed audio/transcription
  lattice/knowledge/tutorial_sentences       — View with embedding index (e5-large-v2)
  lattice/knowledge/research_docs            — Document corpus per tool
  lattice/knowledge/research_chunks          — DocumentSplitter view + embedding index
  lattice/knowledge/skills_registry          — Generated SKILL.md content per tool

Type-surface notes (verified against Pixeltable 0.6.x docs):
  - pxt.Video, pxt.Audio, pxt.Document, pxt.Image, pxt.String are real types
  - No native geometry type in 0.6.x — geometry stays as pxt.String (WKT)
  - Computed columns use t.add_computed_column(col=expr) after create
  - Views use pxt.create_view(path, base_table, iterator=..., ...)
  - Embedding indices use view.add_embedding_index(col, embedding=...)

The computed-column wiring (extract_audio, whisper.transcribe, embeddings)
runs when the migration is applied AND when rows are inserted. At plan-time
this file is committed but NOT executed; Phase 2 of execution runs
`make migrate-dryrun` then `make migrate`.

Ordering: this migration applies after 0014 (lattice/harness). The
lattice/knowledge namespace is independent — no FK dependency on 0014.
"""

from __future__ import annotations

from migrations._helpers import (
    EMBEDDING_MODEL_ID,
    OWNED_PARENTS,
    assert_ownership,
    banner,
    ensure_namespace,
    ensure_table,
)

MIGRATION_ID = "0015_knowledge_substrate"

# Embedding model: intfloat/e5-large-v2 (via shared EMBEDDING_MODEL_ID constant).
# Selected over all-MiniLM-L6-v2 for higher retrieval fidelity on dense
# technical corpora. M3 Max 128 GB RAM makes the 1.3 GB model footprint
# negligible. Decision: 2026-05-11 (user-approved Item 6 override).


# ---------- schemas -------------------------------------------------------

def _tutorials_schema(pxt) -> dict[str, object]:
    """Base columns. Computed columns (audio, audio_meta, transcription)
    are added via t.add_computed_column() after ensure_table returns."""
    return {
        "id":            pxt.String,
        "video":         pxt.Video,
        "source_url":    pxt.String,
        "tool_name":     pxt.String,
        "channel":       pxt.String,
        "title":         pxt.String,
        "view_count":    pxt.Int,
        "published_at":  pxt.Timestamp,
        "ingested_at":   pxt.Timestamp,
        "harvest_run":   pxt.String,
    }


def _research_docs_schema(pxt) -> dict[str, object]:
    return {
        "id":            pxt.String,
        "document":      pxt.Document,
        "source_path":   pxt.String,
        "doc_type":      pxt.String,   # e.g. "api-reference", "tutorial", "blog-post"
        "tool_name":     pxt.String,
        "research_run":  pxt.String,
        "ingested_at":   pxt.Timestamp,
    }


def _skills_registry_schema(pxt) -> dict[str, object]:
    return {
        "id":              pxt.String,
        "skill_name":      pxt.String,
        "tool_name":       pxt.String,
        "skill_content":   pxt.String,
        "source_queries":  pxt.Json,
        "generated_at":    pxt.Timestamp,
        "generation_run":  pxt.String,
        "committed_path":  pxt.String,
    }


# ---------- computed-column + view wiring --------------------------------

def _wire_tutorial_computed_columns(pxt, dry_run: bool) -> dict:
    """Add audio extraction + Whisper transcription as computed columns.

    Pixeltable runs these on every row insert. The exact UDF names match
    the Pixeltable 0.6.x stdlib:
        pxt.functions.video.extract_audio
        pxt.functions.audio.get_metadata
        pxt.functions.huggingface.whisper.transcribe
    """
    out: dict[str, str] = {}
    if dry_run:
        out["tutorials.audio"]         = "would add (extract_audio)"
        out["tutorials.audio_meta"]    = "would add (get_metadata)"
        out["tutorials.transcription"] = "would add (whisper.transcribe model=base.en)"
        return out

    from pixeltable.functions.video import extract_audio
    from pixeltable.functions.audio import get_metadata
    from pixeltable.functions.huggingface import whisper

    t = pxt.get_table("lattice/knowledge/tutorials")
    t.add_computed_column(audio=extract_audio(t.video, format="mp3"), if_exists="ignore")
    out["tutorials.audio"] = "added"
    t.add_computed_column(audio_meta=get_metadata(t.audio), if_exists="ignore")
    out["tutorials.audio_meta"] = "added"
    t.add_computed_column(transcription=whisper.transcribe(audio=t.audio, model="base.en"),
                          if_exists="ignore")
    out["tutorials.transcription"] = "added"
    return out


def _wire_views_and_indices(pxt, dry_run: bool) -> dict:
    """Create the two views + their embedding indices."""
    out: dict[str, str] = {}
    if dry_run:
        out["lattice/knowledge/tutorial_sentences"] = (
            "would create (string_splitter on tutorials.transcription.text, sentence) "
            "+ embedding index (e5-large-v2)"
        )
        out["lattice/knowledge/research_chunks"] = (
            "would create (DocumentSplitter iterator on research_docs.document) "
            "+ embedding index (e5-large-v2)"
        )
        return out

    from pixeltable.iterators.string import StringSplitter as string_splitter
    from pixeltable.iterators.document import DocumentSplitter
    from pixeltable.functions.huggingface import sentence_transformer

    embed = sentence_transformer.using(model_id=EMBEDDING_MODEL_ID)

    tutorials = pxt.get_table("lattice/knowledge/tutorials")
    sent_view = pxt.create_view(
        "lattice/knowledge/tutorial_sentences",
        tutorials,
        iterator=string_splitter.create(
            text=tutorials.transcription.text, separators="sentence"
        ),
        if_exists="ignore",
    )
    sent_view.add_embedding_index("text", embedding=embed, if_exists="ignore")
    out["lattice/knowledge/tutorial_sentences"] = "created + embedding index"

    research = pxt.get_table("lattice/knowledge/research_docs")
    chunk_view = pxt.create_view(
        "lattice/knowledge/research_chunks",
        research,
        iterator=DocumentSplitter.create(
            document=research.document, separators="paragraph", overlap=50
        ),
        if_exists="ignore",
    )
    chunk_view.add_embedding_index("text", embedding=embed, if_exists="ignore")
    out["lattice/knowledge/research_chunks"] = "created + embedding index"

    return out


# ---------- entry point ---------------------------------------------------

def apply(pxt, dry_run: bool) -> dict:
    assert_ownership(pxt, OWNED_PARENTS)
    banner("0015 knowledge substrate (Amendment 07)", dry_run=dry_run)
    out: dict = {}

    # 1. Ancestor namespace must exist (idempotent — earlier migrations created it).
    out["lattice"] = ensure_namespace(pxt, "lattice", dry_run)
    print(f"  lattice                                      -> {out['lattice']}")

    # 2. lattice/knowledge namespace (new in this migration).
    out["lattice/knowledge"] = ensure_namespace(pxt, "lattice/knowledge", dry_run)
    print(f"  lattice/knowledge                            -> {out['lattice/knowledge']}")

    # 3. Base tables.
    tables = {
        "lattice/knowledge/tutorials":       _tutorials_schema(pxt),
        "lattice/knowledge/research_docs":   _research_docs_schema(pxt),
        "lattice/knowledge/skills_registry": _skills_registry_schema(pxt),
    }
    for path, schema in tables.items():
        out[path] = ensure_table(pxt, path, schema, dry_run)
        print(f"  {path:46s} -> {out[path]} ({len(schema)} cols)")

    # 4. Computed columns on tutorials (extract_audio → get_metadata → transcribe).
    out["tutorials.computed"] = _wire_tutorial_computed_columns(pxt, dry_run)
    for k, v in out["tutorials.computed"].items():
        print(f"  {k:46s} -> {v}")

    # 5. Views + embedding indices.
    out["views"] = _wire_views_and_indices(pxt, dry_run)
    for k, v in out["views"].items():
        print(f"  {k:46s} -> {v}")

    return out
