#!/usr/bin/env bash
# install-lattice-cli.sh — install the 'lattice' CLI to ~/.local/bin
#
# Creates a thin wrapper at ~/.local/bin/lattice that delegates to
# scripts/lattice.py via 'uv run'.  The wrapper hard-codes the absolute path
# to this repo so it works from any directory.
#
# Usage:
#   bash scripts/install-lattice-cli.sh
#
# To uninstall:
#   rm ~/.local/bin/lattice

set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || dirname "$(cd "$(dirname "$0")" && pwd)")
SCRIPT_PATH="$REPO_ROOT/scripts/lattice.py"
INSTALL_DIR="$HOME/.local/bin"
INSTALL_PATH="$INSTALL_DIR/lattice"

if [ ! -f "$SCRIPT_PATH" ]; then
  echo "ERROR: $SCRIPT_PATH not found" >&2
  exit 1
fi

mkdir -p "$INSTALL_DIR"

cat > "$INSTALL_PATH" << WRAPPER
#!/usr/bin/env bash
# Auto-generated by install-lattice-cli.sh — do not edit
exec uv run "$SCRIPT_PATH" "\$@"
WRAPPER

chmod +x "$INSTALL_PATH"

echo "✓ Installed lattice CLI at $INSTALL_PATH"
echo ""
echo "Make sure $INSTALL_DIR is on your PATH:"
echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc"
echo ""
echo "Quick start:"
echo "  lattice project list"
echo "  lattice project switch juniper2026"
echo "  lattice project status"
