#!/usr/bin/env bash
# setup-portless.sh — wire stable HTTPS subdomains for LATTICE dev services.
#
# Replaces port numbers with names. Service-level URL stability solves the
# "what port was that?" pain and unlocks secure-context features (WebGPU,
# crypto APIs, secure cookies) for transformers.js + Bonsai-in-browser.
#
# Per-service URL map after setup:
#   https://llm.localhost      → llama-swap (model field selects weights)
#   https://benchy.localhost   → benchy Vue client (was :5173)
#   https://app.localhost      → LATTICE TanStack Start (was :3000/:5173)
#   https://sidecar.localhost  → FastAPI sidecar (was :7770)
#   https://pxt.localhost      → Pixeltable dashboard (was :22089)
#
# Requirements:
#   • bun (LATTICE is bun-only — see ~/.claude/rules/python-uv-only.md
#     and root CLAUDE.md cardinal rules)
#   • macOS / Linux / Windows — portless is cross-platform
#   • Chrome already running (browser-harness attaches to user's browser)
#
# Run from repo root:
#   bash scripts/setup-portless.sh

set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$REPO_ROOT"

YELLOW='\033[0;33m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; RESET='\033[0m'

say() { printf "${CYAN}[setup-portless]${RESET} %s\n" "$*"; }
ok()  { printf "${GREEN}  ✓${RESET} %s\n" "$*"; }
warn(){ printf "${YELLOW}  ! %s${RESET}\n" "$*"; }

# ── 1. Bun must be present (LATTICE is bun-only) ────────────────────────────
if ! command -v bun >/dev/null 2>&1; then
  warn "bun not on PATH. Install: curl -fsSL https://bun.sh/install | bash"
  exit 1
fi
ok "bun $(bun --version)"

# ── 2. Install portless globally via bun (idempotent) ───────────────────────
if ! command -v portless >/dev/null 2>&1; then
  say "Installing portless via bun..."
  bun add -g portless
fi
ok "portless $(portless --version 2>&1 | head -1)"

# ── 3. Per-service .portless.json configs ────────────────────────────────────
#
# Portless reads a config from the working directory when invoked. The config
# file declares the subdomain name; portless then runs the wrapped command
# with $PORT set to an ephemeral assignment.
#
# We write one config per service location. Services that already live in
# subdirectories (benchy/client, etc.) get a config in that subdirectory.

write_config() {
  local dir="$1" name="$2"
  mkdir -p "$dir"
  cat > "$dir/.portless.json" <<JSON
{
  "name": "$name",
  "_doc": "LATTICE Meta-Harness service mapping — auto-generated by scripts/setup-portless.sh"
}
JSON
  ok "$dir/.portless.json → https://$name.localhost"
}

# Llama-swap (the LLM model router — most important one for SFA work)
LLAMA_SWAP_DIR="meta/harness/bin/llama-swap"
if [ -d "$LLAMA_SWAP_DIR" ]; then
  write_config "$LLAMA_SWAP_DIR" "llm"
fi

# Benchy
BENCHY_CLIENT="meta/harness/benchy/client"
BENCHY_SERVER="meta/harness/benchy/server"
[ -d "$BENCHY_CLIENT" ] && write_config "$BENCHY_CLIENT" "benchy"
[ -d "$BENCHY_SERVER" ] && write_config "$BENCHY_SERVER" "benchy-api"

# LATTICE FastAPI sidecar
SIDECAR_DIR="pixeltable/service"
[ -d "$SIDECAR_DIR" ] && write_config "$SIDECAR_DIR" "sidecar"

# LATTICE TanStack app (root if package.json exists with vite/tanstack-start)
if [ -f "package.json" ] && grep -q 'tanstack' package.json 2>/dev/null; then
  write_config "." "app"
fi

# ── 4. Per-service launcher scripts ──────────────────────────────────────────
#
# `portless` is meant to be prepended to a dev command. We ship one tiny
# launcher per service so callers don't need to remember the underlying
# command.

LAUNCHERS_DIR="scripts/portless"
mkdir -p "$LAUNCHERS_DIR"

# LLM launcher (the one the new SFA depends on)
cat > "$LAUNCHERS_DIR/llm.sh" <<'LAUNCHER'
#!/usr/bin/env bash
# Run llama-swap behind https://llm.localhost
set -euo pipefail
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT/meta/harness/bin/llama-swap"
# Portless sets $PORT; llama-swap honors -listen :PORT
exec portless ./llama-swap -config config.yaml -listen ":${PORT:-9090}" -watch-config
LAUNCHER
chmod +x "$LAUNCHERS_DIR/llm.sh"
ok "$LAUNCHERS_DIR/llm.sh"

cat > "$LAUNCHERS_DIR/benchy.sh" <<'LAUNCHER'
#!/usr/bin/env bash
# Run the Benchy Vue client behind https://benchy.localhost
set -euo pipefail
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT/meta/harness/benchy/client"
exec portless bun run dev
LAUNCHER
chmod +x "$LAUNCHERS_DIR/benchy.sh"
ok "$LAUNCHERS_DIR/benchy.sh"

# ── 5. Usage summary ────────────────────────────────────────────────────────
echo
say "Done. Next steps:"
echo
echo "  1. Start the LLM router behind a stable URL:"
echo "       bash scripts/portless/llm.sh"
echo
echo "  2. From any SFA / client, use:"
echo "       base_url = 'https://llm.localhost/v1'"
echo "       model    = 'bonsai-8b' | 'qwen3vl-2b' | …  (any llama-swap entry)"
echo
echo "  3. Visit https://llm.localhost/v1/models in a browser to confirm."
echo
echo "  Stable subdomains live as long as portless is running."
echo "  Stop with Ctrl+C in the launcher window."
