/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsIndexRouteImport } from './routes/threads/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as EvidenceIndexRouteImport } from './routes/evidence/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads/$threadId'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as SettingsPixeltableRouteImport } from './routes/settings/pixeltable'
import { Route as SettingsIntentRouteImport } from './routes/settings/intent'
import { Route as SettingsDbRouteImport } from './routes/settings/db'
import { Route as SettingsAuthRouteImport } from './routes/settings/auth'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ReplayRunIdRouteImport } from './routes/replay/$runId'
import { Route as HarnessCapabilitiesRouteImport } from './routes/harness/capabilities'
import { Route as HarnessBenchmarksRouteImport } from './routes/harness/benchmarks'
import { Route as EvidenceArtifactIdRouteImport } from './routes/evidence/$artifactId'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DemoAiStructuredRouteImport } from './routes/demo/ai-structured'
import { Route as DemoAiImageRouteImport } from './routes/demo/ai-image'
import { Route as DemoAiChatRouteImport } from './routes/demo/ai-chat'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as DemoGuitarsIndexRouteImport } from './routes/demo/guitars/index'
import { Route as DemoGuitarsGuitarIdRouteImport } from './routes/demo/guitars/$guitarId'
import { Route as ApiRuntimeStreamEventsRouteImport } from './routes/api/runtime/stream-events'
import { Route as ApiRuntimeRunAgentRouteImport } from './routes/api/runtime/run-agent'
import { Route as ApiRuntimeOpenrouterRouteImport } from './routes/api/runtime/openrouter'
import { Route as ApiRuntimeListRunsRouteImport } from './routes/api/runtime/list-runs'
import { Route as ApiRuntimeCreateThreadRouteImport } from './routes/api/runtime/create-thread'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoApiAiTtsRouteImport } from './routes/demo/api.ai.tts'
import { Route as DemoApiAiTranscriptionRouteImport } from './routes/demo/api.ai.transcription'
import { Route as DemoApiAiStructuredRouteImport } from './routes/demo/api.ai.structured'
import { Route as DemoApiAiImageRouteImport } from './routes/demo/api.ai.image'
import { Route as DemoApiAiChatRouteImport } from './routes/demo/api.ai.chat'

const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIndexRoute = ThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIndexRoute = EvidenceIndexRouteImport.update({
  id: '/evidence/',
  path: '/evidence/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPixeltableRoute = SettingsPixeltableRouteImport.update({
  id: '/settings/pixeltable',
  path: '/settings/pixeltable',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntentRoute = SettingsIntentRouteImport.update({
  id: '/settings/intent',
  path: '/settings/intent',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDbRoute = SettingsDbRouteImport.update({
  id: '/settings/db',
  path: '/settings/db',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuthRoute = SettingsAuthRouteImport.update({
  id: '/settings/auth',
  path: '/settings/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRunIdRoute = ReplayRunIdRouteImport.update({
  id: '/replay/$runId',
  path: '/replay/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const HarnessCapabilitiesRoute = HarnessCapabilitiesRouteImport.update({
  id: '/harness/capabilities',
  path: '/harness/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const HarnessBenchmarksRoute = HarnessBenchmarksRouteImport.update({
  id: '/harness/benchmarks',
  path: '/harness/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceArtifactIdRoute = EvidenceArtifactIdRouteImport.update({
  id: '/evidence/$artifactId',
  path: '/evidence/$artifactId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiStructuredRoute = DemoAiStructuredRouteImport.update({
  id: '/demo/ai-structured',
  path: '/demo/ai-structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiImageRoute = DemoAiImageRouteImport.update({
  id: '/demo/ai-image',
  path: '/demo/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiChatRoute = DemoAiChatRouteImport.update({
  id: '/demo/ai-chat',
  path: '/demo/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsIndexRoute = DemoGuitarsIndexRouteImport.update({
  id: '/demo/guitars/',
  path: '/demo/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsGuitarIdRoute = DemoGuitarsGuitarIdRouteImport.update({
  id: '/demo/guitars/$guitarId',
  path: '/demo/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeStreamEventsRoute = ApiRuntimeStreamEventsRouteImport.update({
  id: '/api/runtime/stream-events',
  path: '/api/runtime/stream-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeRunAgentRoute = ApiRuntimeRunAgentRouteImport.update({
  id: '/api/runtime/run-agent',
  path: '/api/runtime/run-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeOpenrouterRoute = ApiRuntimeOpenrouterRouteImport.update({
  id: '/api/runtime/openrouter',
  path: '/api/runtime/openrouter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeListRunsRoute = ApiRuntimeListRunsRouteImport.update({
  id: '/api/runtime/list-runs',
  path: '/api/runtime/list-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeCreateThreadRoute = ApiRuntimeCreateThreadRouteImport.update({
  id: '/api/runtime/create-thread',
  path: '/api/runtime/create-thread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTtsRoute = DemoApiAiTtsRouteImport.update({
  id: '/demo/api/ai/tts',
  path: '/demo/api/ai/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTranscriptionRoute = DemoApiAiTranscriptionRouteImport.update({
  id: '/demo/api/ai/transcription',
  path: '/demo/api/ai/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiStructuredRoute = DemoApiAiStructuredRouteImport.update({
  id: '/demo/api/ai/structured',
  path: '/demo/api/ai/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiImageRoute = DemoApiAiImageRouteImport.update({
  id: '/demo/api/ai/image',
  path: '/demo/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiChatRoute = DemoApiAiChatRouteImport.update({
  id: '/demo/api/ai/chat',
  path: '/demo/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/runtime': typeof RuntimeRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/store': typeof DemoStoreRoute
  '/evidence/$artifactId': typeof EvidenceArtifactIdRoute
  '/harness/benchmarks': typeof HarnessBenchmarksRoute
  '/harness/capabilities': typeof HarnessCapabilitiesRoute
  '/replay/$runId': typeof ReplayRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/db': typeof SettingsDbRoute
  '/settings/intent': typeof SettingsIntentRoute
  '/settings/pixeltable': typeof SettingsPixeltableRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/threads/': typeof ThreadsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/runtime/create-thread': typeof ApiRuntimeCreateThreadRoute
  '/api/runtime/list-runs': typeof ApiRuntimeListRunsRoute
  '/api/runtime/openrouter': typeof ApiRuntimeOpenrouterRoute
  '/api/runtime/run-agent': typeof ApiRuntimeRunAgentRoute
  '/api/runtime/stream-events': typeof ApiRuntimeStreamEventsRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/runtime': typeof RuntimeRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/store': typeof DemoStoreRoute
  '/evidence/$artifactId': typeof EvidenceArtifactIdRoute
  '/harness/benchmarks': typeof HarnessBenchmarksRoute
  '/harness/capabilities': typeof HarnessCapabilitiesRoute
  '/replay/$runId': typeof ReplayRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/db': typeof SettingsDbRoute
  '/settings/intent': typeof SettingsIntentRoute
  '/settings/pixeltable': typeof SettingsPixeltableRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/admin': typeof AdminIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/evidence': typeof EvidenceIndexRoute
  '/runs': typeof RunsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/threads': typeof ThreadsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/runtime/create-thread': typeof ApiRuntimeCreateThreadRoute
  '/api/runtime/list-runs': typeof ApiRuntimeListRunsRoute
  '/api/runtime/openrouter': typeof ApiRuntimeOpenrouterRoute
  '/api/runtime/run-agent': typeof ApiRuntimeRunAgentRoute
  '/api/runtime/stream-events': typeof ApiRuntimeStreamEventsRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/guitars': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/runtime': typeof RuntimeRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/store': typeof DemoStoreRoute
  '/evidence/$artifactId': typeof EvidenceArtifactIdRoute
  '/harness/benchmarks': typeof HarnessBenchmarksRoute
  '/harness/capabilities': typeof HarnessCapabilitiesRoute
  '/replay/$runId': typeof ReplayRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/db': typeof SettingsDbRoute
  '/settings/intent': typeof SettingsIntentRoute
  '/settings/pixeltable': typeof SettingsPixeltableRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/threads/': typeof ThreadsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/runtime/create-thread': typeof ApiRuntimeCreateThreadRoute
  '/api/runtime/list-runs': typeof ApiRuntimeListRunsRoute
  '/api/runtime/openrouter': typeof ApiRuntimeOpenrouterRoute
  '/api/runtime/run-agent': typeof ApiRuntimeRunAgentRoute
  '/api/runtime/stream-events': typeof ApiRuntimeStreamEventsRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/runtime'
    | '/agents/$agentId'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/better-auth'
    | '/demo/store'
    | '/evidence/$artifactId'
    | '/harness/benchmarks'
    | '/harness/capabilities'
    | '/replay/$runId'
    | '/runs/$runId'
    | '/settings/auth'
    | '/settings/db'
    | '/settings/intent'
    | '/settings/pixeltable'
    | '/settings/providers'
    | '/threads/$threadId'
    | '/admin/'
    | '/agents/'
    | '/evidence/'
    | '/runs/'
    | '/settings/'
    | '/threads/'
    | '/api/auth/$'
    | '/api/runtime/create-thread'
    | '/api/runtime/list-runs'
    | '/api/runtime/openrouter'
    | '/api/runtime/run-agent'
    | '/api/runtime/stream-events'
    | '/demo/guitars/$guitarId'
    | '/demo/guitars/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/runtime'
    | '/agents/$agentId'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/better-auth'
    | '/demo/store'
    | '/evidence/$artifactId'
    | '/harness/benchmarks'
    | '/harness/capabilities'
    | '/replay/$runId'
    | '/runs/$runId'
    | '/settings/auth'
    | '/settings/db'
    | '/settings/intent'
    | '/settings/pixeltable'
    | '/settings/providers'
    | '/threads/$threadId'
    | '/admin'
    | '/agents'
    | '/evidence'
    | '/runs'
    | '/settings'
    | '/threads'
    | '/api/auth/$'
    | '/api/runtime/create-thread'
    | '/api/runtime/list-runs'
    | '/api/runtime/openrouter'
    | '/api/runtime/run-agent'
    | '/api/runtime/stream-events'
    | '/demo/guitars/$guitarId'
    | '/demo/guitars'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/runtime'
    | '/agents/$agentId'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/better-auth'
    | '/demo/store'
    | '/evidence/$artifactId'
    | '/harness/benchmarks'
    | '/harness/capabilities'
    | '/replay/$runId'
    | '/runs/$runId'
    | '/settings/auth'
    | '/settings/db'
    | '/settings/intent'
    | '/settings/pixeltable'
    | '/settings/providers'
    | '/threads/$threadId'
    | '/admin/'
    | '/agents/'
    | '/evidence/'
    | '/runs/'
    | '/settings/'
    | '/threads/'
    | '/api/auth/$'
    | '/api/runtime/create-thread'
    | '/api/runtime/list-runs'
    | '/api/runtime/openrouter'
    | '/api/runtime/run-agent'
    | '/api/runtime/stream-events'
    | '/demo/guitars/$guitarId'
    | '/demo/guitars/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RuntimeRoute: typeof RuntimeRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  DemoAiChatRoute: typeof DemoAiChatRoute
  DemoAiImageRoute: typeof DemoAiImageRoute
  DemoAiStructuredRoute: typeof DemoAiStructuredRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoStoreRoute: typeof DemoStoreRoute
  EvidenceArtifactIdRoute: typeof EvidenceArtifactIdRoute
  HarnessBenchmarksRoute: typeof HarnessBenchmarksRoute
  HarnessCapabilitiesRoute: typeof HarnessCapabilitiesRoute
  ReplayRunIdRoute: typeof ReplayRunIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  SettingsAuthRoute: typeof SettingsAuthRoute
  SettingsDbRoute: typeof SettingsDbRoute
  SettingsIntentRoute: typeof SettingsIntentRoute
  SettingsPixeltableRoute: typeof SettingsPixeltableRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  EvidenceIndexRoute: typeof EvidenceIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ThreadsIndexRoute: typeof ThreadsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRuntimeCreateThreadRoute: typeof ApiRuntimeCreateThreadRoute
  ApiRuntimeListRunsRoute: typeof ApiRuntimeListRunsRoute
  ApiRuntimeOpenrouterRoute: typeof ApiRuntimeOpenrouterRoute
  ApiRuntimeRunAgentRoute: typeof ApiRuntimeRunAgentRoute
  ApiRuntimeStreamEventsRoute: typeof ApiRuntimeStreamEventsRoute
  DemoGuitarsGuitarIdRoute: typeof DemoGuitarsGuitarIdRoute
  DemoGuitarsIndexRoute: typeof DemoGuitarsIndexRoute
  DemoApiAiChatRoute: typeof DemoApiAiChatRoute
  DemoApiAiImageRoute: typeof DemoApiAiImageRoute
  DemoApiAiStructuredRoute: typeof DemoApiAiStructuredRoute
  DemoApiAiTranscriptionRoute: typeof DemoApiAiTranscriptionRoute
  DemoApiAiTtsRoute: typeof DemoApiAiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/': {
      id: '/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof ThreadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/': {
      id: '/evidence/'
      path: '/evidence'
      fullPath: '/evidence/'
      preLoaderRoute: typeof EvidenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/pixeltable': {
      id: '/settings/pixeltable'
      path: '/settings/pixeltable'
      fullPath: '/settings/pixeltable'
      preLoaderRoute: typeof SettingsPixeltableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/intent': {
      id: '/settings/intent'
      path: '/settings/intent'
      fullPath: '/settings/intent'
      preLoaderRoute: typeof SettingsIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/db': {
      id: '/settings/db'
      path: '/settings/db'
      fullPath: '/settings/db'
      preLoaderRoute: typeof SettingsDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/auth': {
      id: '/settings/auth'
      path: '/settings/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof SettingsAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay/$runId': {
      id: '/replay/$runId'
      path: '/replay/$runId'
      fullPath: '/replay/$runId'
      preLoaderRoute: typeof ReplayRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness/capabilities': {
      id: '/harness/capabilities'
      path: '/harness/capabilities'
      fullPath: '/harness/capabilities'
      preLoaderRoute: typeof HarnessCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness/benchmarks': {
      id: '/harness/benchmarks'
      path: '/harness/benchmarks'
      fullPath: '/harness/benchmarks'
      preLoaderRoute: typeof HarnessBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/$artifactId': {
      id: '/evidence/$artifactId'
      path: '/evidence/$artifactId'
      fullPath: '/evidence/$artifactId'
      preLoaderRoute: typeof EvidenceArtifactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-structured': {
      id: '/demo/ai-structured'
      path: '/demo/ai-structured'
      fullPath: '/demo/ai-structured'
      preLoaderRoute: typeof DemoAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-image': {
      id: '/demo/ai-image'
      path: '/demo/ai-image'
      fullPath: '/demo/ai-image'
      preLoaderRoute: typeof DemoAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-chat': {
      id: '/demo/ai-chat'
      path: '/demo/ai-chat'
      fullPath: '/demo/ai-chat'
      preLoaderRoute: typeof DemoAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/': {
      id: '/demo/guitars/'
      path: '/demo/guitars'
      fullPath: '/demo/guitars/'
      preLoaderRoute: typeof DemoGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/$guitarId': {
      id: '/demo/guitars/$guitarId'
      path: '/demo/guitars/$guitarId'
      fullPath: '/demo/guitars/$guitarId'
      preLoaderRoute: typeof DemoGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/stream-events': {
      id: '/api/runtime/stream-events'
      path: '/api/runtime/stream-events'
      fullPath: '/api/runtime/stream-events'
      preLoaderRoute: typeof ApiRuntimeStreamEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/run-agent': {
      id: '/api/runtime/run-agent'
      path: '/api/runtime/run-agent'
      fullPath: '/api/runtime/run-agent'
      preLoaderRoute: typeof ApiRuntimeRunAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/openrouter': {
      id: '/api/runtime/openrouter'
      path: '/api/runtime/openrouter'
      fullPath: '/api/runtime/openrouter'
      preLoaderRoute: typeof ApiRuntimeOpenrouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/list-runs': {
      id: '/api/runtime/list-runs'
      path: '/api/runtime/list-runs'
      fullPath: '/api/runtime/list-runs'
      preLoaderRoute: typeof ApiRuntimeListRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/create-thread': {
      id: '/api/runtime/create-thread'
      path: '/api/runtime/create-thread'
      fullPath: '/api/runtime/create-thread'
      preLoaderRoute: typeof ApiRuntimeCreateThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/tts': {
      id: '/demo/api/ai/tts'
      path: '/demo/api/ai/tts'
      fullPath: '/demo/api/ai/tts'
      preLoaderRoute: typeof DemoApiAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/transcription': {
      id: '/demo/api/ai/transcription'
      path: '/demo/api/ai/transcription'
      fullPath: '/demo/api/ai/transcription'
      preLoaderRoute: typeof DemoApiAiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/structured': {
      id: '/demo/api/ai/structured'
      path: '/demo/api/ai/structured'
      fullPath: '/demo/api/ai/structured'
      preLoaderRoute: typeof DemoApiAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/image': {
      id: '/demo/api/ai/image'
      path: '/demo/api/ai/image'
      fullPath: '/demo/api/ai/image'
      preLoaderRoute: typeof DemoApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/chat': {
      id: '/demo/api/ai/chat'
      path: '/demo/api/ai/chat'
      fullPath: '/demo/api/ai/chat'
      preLoaderRoute: typeof DemoApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RuntimeRoute: RuntimeRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  DemoAiChatRoute: DemoAiChatRoute,
  DemoAiImageRoute: DemoAiImageRoute,
  DemoAiStructuredRoute: DemoAiStructuredRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoStoreRoute: DemoStoreRoute,
  EvidenceArtifactIdRoute: EvidenceArtifactIdRoute,
  HarnessBenchmarksRoute: HarnessBenchmarksRoute,
  HarnessCapabilitiesRoute: HarnessCapabilitiesRoute,
  ReplayRunIdRoute: ReplayRunIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  SettingsAuthRoute: SettingsAuthRoute,
  SettingsDbRoute: SettingsDbRoute,
  SettingsIntentRoute: SettingsIntentRoute,
  SettingsPixeltableRoute: SettingsPixeltableRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  EvidenceIndexRoute: EvidenceIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRuntimeCreateThreadRoute: ApiRuntimeCreateThreadRoute,
  ApiRuntimeListRunsRoute: ApiRuntimeListRunsRoute,
  ApiRuntimeOpenrouterRoute: ApiRuntimeOpenrouterRoute,
  ApiRuntimeRunAgentRoute: ApiRuntimeRunAgentRoute,
  ApiRuntimeStreamEventsRoute: ApiRuntimeStreamEventsRoute,
  DemoGuitarsGuitarIdRoute: DemoGuitarsGuitarIdRoute,
  DemoGuitarsIndexRoute: DemoGuitarsIndexRoute,
  DemoApiAiChatRoute: DemoApiAiChatRoute,
  DemoApiAiImageRoute: DemoApiAiImageRoute,
  DemoApiAiStructuredRoute: DemoApiAiStructuredRoute,
  DemoApiAiTranscriptionRoute: DemoApiAiTranscriptionRoute,
  DemoApiAiTtsRoute: DemoApiAiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
